apiVersion: apps/v1
kind: Deployment
metadata:
  name: handy-server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: handy-server
  template:
    metadata:
      labels:
        app: handy-server
    spec:
      containers:
      - name: handy
        image: docker.korshakov.com/handy-server:{version}
        ports:
        - containerPort: 3005
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3005"
        - name: DATABASE_URL
          value: file:./prisma/dev.db
        - name: HANDY_MASTER_SECRET
          value: your-super-secret-key-for-single-user-deployment
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: handy-server-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: handy-server
---
apiVersion: v1
kind: Service
metadata:
  name: handy-server
spec:
  selector:
    app: handy-server
  ports:
  - port: 3000
    targetPort: 3005
  type: ClusterIP